### PR TITLE
Ambiguity of parseInt radix

### PR DESCRIPTION
**Pull request by gsmaverick**
These changes remove the ambiguity of the radix used for the parseInt calls.  More details can be found on MDN: https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/parseInt#Description

### CODE REVIEW

**Comment by jazzychad** [comment]
sweet, thanks for the fix.

**Comment by jazzychad** [comment]
i'm sure the tests will still pass with the diff, but did you happen to run the unit tests? if not i can run them before i merge.

**Comment by gsmaverick** [comment]
No I did not.

**Comment by jazzychad** [comment]
ran tests, passed. merged in commit. thanks!

**Pull request merged**
