### PR TITLE
Fixed undefined values on sets when using BankersBoxNullAdapter

### PR DESCRIPTION
**Pull request by guillaumepotier**
Hi,

I found two errors while using sets data (`sadd`, `srem`..) and the `BankersBoxNullAdapter`.

Here is a small PR that only checks if value is not undefined.

### CODE REVIEW

**Comment by jazzychad** [comment]
Hey @guillaumepotier, thanks for pointing out this issue. Could you give an example of when this bug occurs? I'd like to add a test(s) for it and then fix it... I think it is probably better to change the "get_raw" function to return null in the case of undefined instead of checking for multiple 'empty' values in multiple places...

**Comment by jazzychad** [comment]
In fact, this might even be solved by having BankersBoxNullAdapter.getItem return null instead of undefined (which is probably more 'correct' anyway). Either way I still think we should also do the undefined check in get_raw as well.

**Comment by guillaumepotier** [comment]
Hi @jazzychad, I'll try to reproduce the issue on a jsfiddle to allow you consigning the fix in the test suite.

And yes, the `BankersBoxNullAdapter.getItem` should definitely return null that seems more the good way.

Best

**Comment by jazzychad** [comment]
This has been fixed in the latest code push.

**Pull request closed without merging**
